-- Migration 012: Domain strategy layer
-- ALREADY RUN in Supabase SQL Editor. Kept here for reference.

ALTER TABLE projects ADD COLUMN domain_strategy JSONB DEFAULT '{}';
COMMENT ON COLUMN projects.domain_strategy IS
'Holistic AEO domain strategy. Generated by AI analysis of all crawled pages.
Contains: domain_summary, page_roles, cannibalisation, gaps, strategic_rules.
Injected into every playbook prompt to differentiate recommendations per page.';

ALTER TABLE projects ADD COLUMN domain_strategy_generated_at TIMESTAMPTZ;

NOTIFY pgrst, 'reload schema';
